spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://hsadmin:Sydney_0509@ac-8p1cykl-shard-00-00.bnmvnin.mongodb.net:27017,ac-8p1cykl-shard-00-01.bnmvnin.mongodb.net:27017,ac-8p1cykl-shard-00-02.bnmvnin.mongodb.net:27017/auth_db?ssl=true&replicaSet=atlas-tzcxgu-shard-0&authSource=admin&appName=housing-society-cluster

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: change-this-to-a-very-long-secret-key-for-development
      access-token-expiration: 900000
      refresh-token-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO