spring:
  application:
    name: auth-service

server:
  port: 8081

data:
  mongodb:
    host: localhost
    port: 27017
    database: housing_society_management

application:
  security:
    jwt:
      secret-key: change-this-to-a-very-long-secret-key-for-development
      access-token-expiration: 900000
      refresh-token-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always