spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  application:
    name: auth-service

  data:
    mongodb:
      uri: ${AUTH_MONGODB_URI}

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  cloud:
    discovery:
      enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

