spring:
  application:
    name: society-service

  data:
    mongodb:
      uri: ${SOCIETY_MONGODB_URI}

  cloud:
    discovery:
      enabled: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret-key: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO